language: node_js
node_js:
  - '7'
notifications:
  email:
    on_failure: change
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  'on':
    branch: master
    node: '7'
env:
  global:
    - secure: >-
        JmH1Vv6Ue2Z/d36uRBw3cCNRabvFuqEabWdO6Rhh/sfedo0J0915TyRF6iVw+c5JjHzFnOanCGg7U3gITstHcenNxAs5spyw3RBZsofT/qPd23gcj1sz07N9P223BpVZckxLdGAM3H9zXB9YFLWOXoZ52/7OuN7/a6Wu5uOK6wUE7DXUzySzaHN7O4flwOi5KeBM3jusgGYq7MFCGAxoMVzMe/jmbOpy7N/LN24SwzSiqCPQtht6cZhXYdFRPuMmIlIpyHQnGv8jtArkHHO77k3HFqANNf+a07gwiO4N1Qm3JMpytycXXFgt+283zaOgffkyvctDp+3Yg+qkLF+L4qDh3Nez7AcmKg68u2UfN6FptV1STTjYi4p61B19Cq5t+goidpYg0lzRdXZqPqLz8YPQxrujPKNek4p98ZyFbmxKYZop0ZwlecIe63krbuO/7cDdRbUhyyyoHZEiNuPLEuk2dOXKCZ9mc6NYFllKI7fkKnhvgxLCQqm7kj0FD/ltvQlgF9Lolf2+06ViCK0T7/TTDOaxVxixkvNTqmRWsGZjU0rYk7zlgp9usYZRlG76TwuxQ19roAGlwq0KWOEBnYMGQIPwBVz0TnBr7bMr5WqwIVFr3QNbI9G9gc2h9l6OSWtuS2mKKyUpRlr9c/EOoEFPZkDVMFwX5Vvbuo+GQKg=
    - 'GIT_DEPLOY_REPO=https://$GH_TOKEN@github.com/postcss/postcss.org.git'
    - GIT_DEPLOY_DIR=dist
